const ALL_COUPLES_PHOTO_PATHS = [
    '/couples_photo/IMG_0039.webp',
    '/couples_photo/IMG_0067.webp',
    '/couples_photo/IMG_0295.webp',
    '/couples_photo/IMG_0398.webp',
    '/couples_photo/IMG_0400.webp',
    '/couples_photo/IMG_0488.webp',
    '/couples_photo/IMG_0666.webp',
    '/couples_photo/IMG_0725.webp',
    '/couples_photo/IMG_0781.webp',
    '/couples_photo/IMG_1045.webp',
    '/couples_photo/IMG_1289.webp',
    '/couples_photo/IMG_1410.webp',
    '/couples_photo/IMG_1423.webp',
    '/couples_photo/IMG_1430.webp',
    '/couples_photo/IMG_1527.webp',
    '/couples_photo/IMG_1989.webp',
    '/couples_photo/IMG_2019.webp',
    '/couples_photo/IMG_2104.webp',
    '/couples_photo/IMG_2192.webp',
    '/couples_photo/IMG_2276.webp',
    '/couples_photo/IMG_2301.webp',
    '/couples_photo/IMG_2354_2.webp',
    '/couples_photo/IMG_2356_2.webp',
    '/couples_photo/IMG_2619.webp',
    '/couples_photo/IMG_2626.webp',
    '/couples_photo/IMG_2650.webp',
    '/couples_photo/IMG_2659.webp',
    '/couples_photo/IMG_2734.webp',
    '/couples_photo/IMG_2834.webp',
    '/couples_photo/IMG_2842.webp',
    '/couples_photo/IMG_2844.webp',
    '/couples_photo/IMG_2874.webp',
    '/couples_photo/IMG_3193.webp',
    '/couples_photo/IMG_3290.webp',
    '/couples_photo/IMG_3305.webp',
    '/couples_photo/IMG_3338.webp',
    '/couples_photo/IMG_3364.webp',
    '/couples_photo/IMG_3407.webp',
    '/couples_photo/IMG_3505.webp',
    '/couples_photo/IMG_3512.webp',
    '/couples_photo/IMG_3807.webp',
    '/couples_photo/IMG_3872.webp',
    '/couples_photo/IMG_3912.webp',
    '/couples_photo/IMG_4101.webp',
    '/couples_photo/IMG_4158.webp',
    '/couples_photo/IMG_4222.webp',
    '/couples_photo/IMG_4384.webp',
    '/couples_photo/IMG_4624.webp',
    '/couples_photo/IMG_4663.webp',
    '/couples_photo/IMG_4689.webp',
    '/couples_photo/IMG_4698.webp',
    '/couples_photo/IMG_4745.webp',
    '/couples_photo/IMG_4813.webp',
    '/couples_photo/IMG_4827.webp',
    '/couples_photo/IMG_4878.webp',
    '/couples_photo/IMG_4892.webp',
    '/couples_photo/IMG_4918.webp',
    '/couples_photo/IMG_5087.webp',
    '/couples_photo/IMG_5200.webp',
    '/couples_photo/IMG_5235.webp',
    '/couples_photo/IMG_5350.webp',
    '/couples_photo/IMG_5429.webp',
    '/couples_photo/IMG_5442.webp',
    '/couples_photo/IMG_5523.webp',
    '/couples_photo/IMG_5531.webp',
    '/couples_photo/IMG_5547.webp',
    '/couples_photo/IMG_5551.webp',
    '/couples_photo/IMG_5715.webp',
    '/couples_photo/IMG_5760.webp',
    '/couples_photo/IMG_5763.webp',
    '/couples_photo/IMG_5817.webp',
    '/couples_photo/IMG_5855.webp',
    '/couples_photo/IMG_5913.webp',
    '/couples_photo/IMG_5922.webp',
    '/couples_photo/IMG_6062.webp',
    '/couples_photo/IMG_6119.webp',
    '/couples_photo/IMG_6195.webp',
    '/couples_photo/IMG_6208.webp',
    '/couples_photo/IMG_6241.webp',
    '/couples_photo/IMG_6246.webp',
    '/couples_photo/IMG_6248.webp',
    '/couples_photo/IMG_6304.webp',
    '/couples_photo/IMG_6327.webp',
    '/couples_photo/IMG_6352.webp',
    '/couples_photo/IMG_6368.webp',
    '/couples_photo/IMG_6564.webp',
    '/couples_photo/IMG_6658.webp',
    '/couples_photo/IMG_6681.webp',
    '/couples_photo/IMG_6750.webp',
    '/couples_photo/IMG_6865.webp',
    '/couples_photo/IMG_6919.webp',
    '/couples_photo/IMG_6974.webp',
    '/couples_photo/IMG_7007.webp',
    '/couples_photo/IMG_7138.webp',
    '/couples_photo/IMG_7349.webp',
    '/couples_photo/IMG_7451.webp',
    '/couples_photo/IMG_7568.webp',
    '/couples_photo/IMG_7579.webp',
    '/couples_photo/IMG_7591.webp',
    '/couples_photo/IMG_7592.webp',
    '/couples_photo/IMG_7598.webp',
    '/couples_photo/IMG_7621.webp',
    '/couples_photo/IMG_7649.webp',
    '/couples_photo/IMG_7669.webp',
    '/couples_photo/IMG_7752.webp',
    '/couples_photo/IMG_7805_2.webp',
    '/couples_photo/IMG_7805.webp',
    '/couples_photo/IMG_7987.webp',
    '/couples_photo/IMG_8026.webp',
    '/couples_photo/IMG_8263.webp',
    '/couples_photo/IMG_8267.webp',
    '/couples_photo/IMG_8320.webp',
    '/couples_photo/IMG_8464.webp',
    '/couples_photo/IMG_8476.webp',
    '/couples_photo/IMG_8485.webp',
    '/couples_photo/IMG_8524.webp',
    '/couples_photo/IMG_8530.webp',
    '/couples_photo/IMG_8630.webp',
    '/couples_photo/IMG_8686.webp',
    '/couples_photo/IMG_8688.webp',
    '/couples_photo/IMG_8695.webp',
    '/couples_photo/IMG_8731.webp',
    '/couples_photo/IMG_8803.webp',
    '/couples_photo/IMG_8861.webp',
    '/couples_photo/IMG_8862.webp',
    '/couples_photo/IMG_8864.webp',
    '/couples_photo/IMG_8865.webp',
    '/couples_photo/IMG_8870.webp',
    '/couples_photo/IMG_8874.webp',
    '/couples_photo/IMG_8877.webp',
    '/couples_photo/IMG_8878.webp',
    '/couples_photo/IMG_8879.webp',
    '/couples_photo/IMG_8880.webp',
    '/couples_photo/IMG_8885.webp',
    '/couples_photo/IMG_8890.webp',
    '/couples_photo/IMG_8892.webp',
    '/couples_photo/IMG_8927.webp',
    '/couples_photo/IMG_9075.webp',
    '/couples_photo/IMG_9245.webp',
    '/couples_photo/IMG_9247.webp',
    '/couples_photo/IMG_9673.webp',
    '/couples_photo/IMG_9738.webp',
    '/couples_photo/IMG_9748.webp',
    '/couples_photo/IMG_9804.webp',
    '/couples_photo/IMG_9915.webp',
    '/couples_photo/IMG_9961.webp',
];

// Only a handful of photos are actually shown in the 3D gallery room — loading
// the full set (146 photos) as GPU textures was crashing the tab on phones.
// Increase this number if devices can handle more; keep the full list above
// so it's easy to swap which ones show later.
//
// Photos are sampled EVENLY across the whole list, ordered by the numeric ID in
// each file name (IMG_XXXX), so the gallery mixes older and newer photos instead
// of only showing the oldest ones.
const GALLERY_PHOTO_LIMIT = 40;

const getFileNumber = (path) => {
    const match = path.match(/(\d+)(?:_\d+)?\.\w+$/);
    return match ? parseInt(match[1], 10) : 0;
};

const SORTED_BY_FILENAME = [...ALL_COUPLES_PHOTO_PATHS].sort((a, b) => getFileNumber(a) - getFileNumber(b));

const sampleEvenly = (items, count) => {
    if (count >= items.length) return items;
    const step = items.length / count;
    return Array.from({ length: count }, (_, i) => items[Math.floor(i * step)]);
};

export const COUPLES_PHOTO_PATHS = sampleEvenly(SORTED_BY_FILENAME, GALLERY_PHOTO_LIMIT);
